<?php

declare(strict_types=1);

namespace Mulkihawler\Tooling;

use RuntimeException;

/**
 * The provenance of a source tree: which baseline it descends from, what it
 * actually contains now, and which archive carries it.
 *
 * The previous edition collapsed all of that into one field. It accepted an
 * operator-supplied 40-character commit and reported the tree as "representing"
 * it — so a tree carrying uncommitted v7 changes was described as being commit
 * 9c0188f8, which is the v6 baseline and emphatically not what the files
 * contain. It then proved integrity against the tree's OWN internal
 * SHA256SUMS.txt, which is self-authenticating: change a file and its manifest
 * line together and verification still passes. And because it only walked the
 * entries the manifest listed, an unlisted extra file was invisible.
 *
 * Three distinct identities are therefore kept distinct:
 *
 *   baseline_commit            the committed ancestor. A label, never a claim
 *                              about the current files.
 *   final_tree_manifest_sha256 what the tree contains NOW, derived from a
 *                              deterministic complete manifest.
 *   source_archive_sha256      which archive carries it.
 *
 * The manifest is trusted only when its hash is supplied from OUTSIDE the
 * archive it describes — a detached value the operator carries separately.
 * Without that, an edit that rewrites both the files and the manifest is
 * undetectable, and this class says so instead of passing.
 *
 * The file set is compared in both directions: every manifest entry must exist,
 * and every eligible file on disk must be listed. Paths are validated before
 * they are used, because a manifest is untrusted input until proven otherwise.
 */
final class SourceIdentity
{
    public const SOURCE_GIT = 'git';

    public const SOURCE_MANIFEST = 'manifest';

    public const MANIFEST_NAME = 'TREE_MANIFEST.txt';

    /**
     * The exclusion policy, versioned because the manifest is only reproducible
     * if both ends agree on what "eligible" means. Bump this when the set
     * changes; evidence recorded under an older policy is not comparable.
     */
    public const EXCLUSION_POLICY_VERSION = 2;

    /** Directories never eligible for the manifest. */
    public const EXCLUDED_DIRS = [
        '.git',
        'vendor',
        'node_modules',
        'storage/framework',
        'storage/logs',
        'storage/app/public',
        'bootstrap/cache',
        '.phpunit.cache',
        'dist',
        /*
         * Python bytecode caches. Omitting these let `python3 -m py_compile`
         * regenerate a .pyc between the manifest walk and the archive staging,
         * so the manifest listed a file the archive did not contain. Anything
         * a tool can recreate on its own must be excluded, or the manifest
         * describes a moment rather than a tree.
         */
        '__pycache__',
    ];

    /** Exact paths never eligible, relative to the project root. */
    public const EXCLUDED_FILES = [
        '.env',
        '.env.local',
        '.env.production',
        'auth.json',
        self::MANIFEST_NAME,
        /*
         * The detached hash is the binding FOR the manifest, so it cannot be
         * part of what the manifest describes — including it would make the
         * document contain a hash of a file that contains its own hash. It is
         * meant to travel outside the archive anyway.
         */
        'TREE_MANIFEST.sha256',
        /*
         * Derived from the same eligible set as TREE_MANIFEST, so it cannot be
         * part of what it describes. Keeping it eligible meant two manifests
         * covering two slightly different sets — the dual-source problem that
         * produced the bytecode mismatch.
         */
        'SHA256SUMS.txt',
        /*
         * Generated by the browser fixture seeder. It carries a known test
         * password and two MFA seeds, and it shipped inside the authenticated
         * tree while the comments claimed it was excluded. Excluding it from
         * the manifest alone would not be enough — a delivered unauthenticated
         * credential file is still a defect — so staging purges it and the
         * secret scan fails when it is present.
         */
        'tests/Browser/support/fixtures.json',
    ];

    /** Suffixes never eligible: editor leftovers, merge debris, volatile data. */
    public const EXCLUDED_SUFFIXES = [
        '.bak',
        '.orig',
        '.rej',
        '.swp',
        '.swo',
        '~',
        '.sqlite',
        '.log',
        '.pyc',
        '.pyo',
    ];

    private function __construct(
        public readonly ?string $baselineCommit,
        public readonly string $finalTreeManifestSha256,
        public readonly ?string $sourceArchiveSha256,
        public readonly string $source,
        public readonly int $filesVerified,
        public readonly string $integrityProof,
        public readonly bool $externallyBound,
    ) {}

    /**
     * Resolve provenance for the tree at $root.
     *
     * @param  list<string>  $argv
     *
     * @throws RuntimeException when provenance cannot be proved
     */
    public static function resolve(string $root, array $argv = []): self
    {
        $root = self::realRoot($root);
        $baseline = self::option($argv, 'baseline-commit') ?? self::environment('MYHAWLER_BASELINE_COMMIT');

        if ($baseline !== null && ! self::looksLikeCommit($baseline)) {
            throw new RuntimeException(
                'the supplied baseline commit '.var_export($baseline, true)
                .' is not a 40-character hexadecimal commit id.'
            );
        }

        $archiveHash = null;
        $archive = self::option($argv, 'source-archive');

        if ($archive !== null) {
            if (! is_file($archive)) {
                throw new RuntimeException('the source archive '.$archive.' does not exist.');
            }

            $archiveHash = (string) hash_file('sha256', $archive);
        }

        $allowSymlinks = in_array('--allow-symlinks', $argv, true);
        $manifestPath = self::option($argv, 'tree-manifest') ?? $root.'/'.self::MANIFEST_NAME;
        $trusted = self::option($argv, 'trusted-manifest-sha256')
            ?? self::environment('MYHAWLER_TRUSTED_MANIFEST_SHA256');

        if (self::isGitWorkingTree($root)) {
            return self::fromGit($root, $baseline, $archiveHash, $allowSymlinks);
        }

        return self::fromManifest($root, $baseline, $archiveHash, $manifestPath, $trusted, $allowSymlinks);
    }

    /**
     * Build the deterministic complete manifest for a tree.
     *
     * Sorted by byte value, LF endings, sha256sum format. Two runs over
     * identical content must produce identical bytes, or the manifest hash
     * means nothing.
     *
     * @return array{manifest: string, files: list<string>}
     *
     * @throws RuntimeException
     */
    public static function buildManifest(string $root, bool $allowSymlinks = false): array
    {
        $root = self::realRoot($root);
        $files = self::eligibleFiles($root, $allowSymlinks);
        sort($files, SORT_STRING);

        $lines = '';

        foreach ($files as $relative) {
            $lines .= hash_file('sha256', $root.'/'.$relative).'  '.$relative."\n";
        }

        return ['manifest' => $lines, 'files' => $files];
    }

    /**
     * Every file eligible for the manifest, as root-relative paths.
     *
     * @return list<string>
     *
     * @throws RuntimeException
     */
    public static function eligibleFiles(string $root, bool $allowSymlinks = false): array
    {
        $root = self::realRoot($root);
        $found = [];

        $walk = static function (string $dir, string $prefix) use (&$walk, $allowSymlinks, &$found): void {
            $entries = scandir($dir);

            if ($entries === false) {
                throw new RuntimeException('could not read the directory '.$dir);
            }

            foreach ($entries as $entry) {
                if ($entry === '.' || $entry === '..') {
                    continue;
                }

                $path = $dir.'/'.$entry;
                $relative = $prefix === '' ? $entry : $prefix.'/'.$entry;

                if (is_link($path)) {
                    if (! $allowSymlinks) {
                        throw new RuntimeException(
                            'the tree contains a symlink at '.$relative
                            .'; symlinks change meaning when archived and are refused unless '
                            .'--allow-symlinks is given explicitly.'
                        );
                    }

                    continue;
                }

                if (is_dir($path)) {
                    if (! self::isExcludedDir($relative)) {
                        $walk($path, $relative);
                    }

                    continue;
                }

                if (! self::isExcludedFile($relative)) {
                    $found[] = $relative;
                }
            }
        };

        $walk($root, '');

        return $found;
    }

    public static function isExcludedDir(string $relative): bool
    {
        foreach (self::EXCLUDED_DIRS as $excluded) {
            if ($relative === $excluded || str_starts_with($relative, $excluded.'/')) {
                return true;
            }

            if (! str_contains($excluded, '/') && str_ends_with($relative, '/'.$excluded)) {
                return true;
            }
        }

        return false;
    }

    public static function isExcludedFile(string $relative): bool
    {
        if (in_array($relative, self::EXCLUDED_FILES, true)) {
            return true;
        }

        foreach (self::EXCLUDED_SUFFIXES as $suffix) {
            if (str_ends_with($relative, $suffix)) {
                return true;
            }
        }

        // `.backup-20260802-014031` and every other dated variant.
        return (bool) preg_match('/\.backup(-[\w.-]+)?$/', $relative);
    }

    /**
     * Validate one manifest path before it is ever turned into a filesystem
     * path. A manifest is untrusted input until this passes.
     *
     * @return string|null the reason it is unsafe, or null when safe
     */
    public static function unsafePathReason(string $relative): ?string
    {
        if ($relative === '') {
            return 'empty path';
        }

        if (str_contains($relative, "\0")) {
            return 'contains a NUL byte';
        }

        if (str_starts_with($relative, '/') || preg_match('#^[A-Za-z]:[\\\\/]#', $relative) === 1) {
            return 'absolute path';
        }

        if (str_contains($relative, '\\')) {
            return 'backslash separator';
        }

        foreach (explode('/', $relative) as $segment) {
            if ($segment === '..') {
                return 'parent-directory traversal';
            }

            if ($segment === '') {
                return 'empty path segment';
            }
        }

        return null;
    }

    /**
     * @throws RuntimeException
     */
    private static function fromGit(
        string $root,
        ?string $baseline,
        ?string $archiveHash,
        bool $allowSymlinks,
    ): self {
        $git = 'git -C '.escapeshellarg($root).' ';
        $status = self::run($git.'status --porcelain');

        if ($status['code'] !== 0) {
            throw new RuntimeException('git is present but could not report the working-tree status.');
        }

        $head = trim(self::run($git.'rev-parse HEAD')['output']);
        $dirty = trim($status['output']) !== '';

        /*
         * A dirty checkout is allowed, unlike before, because this project
         * legitimately carries uncommitted v7 work. What is NOT allowed is
         * calling the result "commit HEAD". The manifest hash describes the
         * files; HEAD is recorded only as the ancestor.
         */
        $built = self::buildManifest($root, $allowSymlinks);

        return new self(
            $baseline ?? (self::looksLikeCommit($head) ? $head : null),
            hash('sha256', $built['manifest']),
            $archiveHash,
            self::SOURCE_GIT,
            count($built['files']),
            $dirty
                ? 'git checkout with uncommitted changes; identity computed from the tree manifest, not from HEAD'
                : 'git checkout clean against HEAD; identity computed from the tree manifest',
            false,
        );
    }

    /**
     * @throws RuntimeException
     */
    private static function fromManifest(
        string $root,
        ?string $baseline,
        ?string $archiveHash,
        string $manifestPath,
        ?string $trusted,
        bool $allowSymlinks,
    ): self {
        if (! is_file($manifestPath)) {
            throw new RuntimeException(
                'this is not a git working tree and there is no '.self::MANIFEST_NAME
                .', so the tree cannot be identified. Pass --tree-manifest=<path>.'
            );
        }

        $raw = (string) file_get_contents($manifestPath);
        $manifestHash = hash('sha256', $raw);

        /*
         * The detached hash is the whole point. Without it the manifest proves
         * only that the tree is internally consistent, which a single edit to
         * both file and manifest also achieves.
         */
        if ($trusted === null) {
            throw new RuntimeException(
                'no trusted manifest hash was supplied, so '.self::MANIFEST_NAME
                ." is self-authenticating and proves nothing.\n"
                .'Pass --trusted-manifest-sha256=<sha> (or set MYHAWLER_TRUSTED_MANIFEST_SHA256) '
                .'with the detached value carried outside the archive.'
            );
        }

        if (preg_match('/^[0-9a-f]{64}$/', $trusted) !== 1) {
            throw new RuntimeException('the trusted manifest hash is not a 64-character hexadecimal digest.');
        }

        if (! hash_equals($trusted, $manifestHash)) {
            throw new RuntimeException(
                self::MANIFEST_NAME.' does not match the trusted detached hash.'
                ."\n  expected {$trusted}\n  actual   {$manifestHash}"
            );
        }

        [$listed, $problems] = self::verifyManifestEntries($root, $raw);

        // Both directions: nothing missing, and nothing unlisted.
        $onDisk = self::eligibleFiles($root, $allowSymlinks);

        foreach (array_diff($onDisk, array_keys($listed)) as $extra) {
            $problems[] = $extra.': present in the tree but absent from the manifest';
        }

        if ($problems !== []) {
            $shown = array_slice($problems, 0, 12);
            $more = count($problems) - count($shown);

            throw new RuntimeException(
                self::MANIFEST_NAME.' does not describe this tree:'
                ."\n  ".implode("\n  ", $shown)
                .($more > 0 ? "\n  ... and {$more} more" : '')
            );
        }

        if ($listed === []) {
            throw new RuntimeException(self::MANIFEST_NAME.' lists no files.');
        }

        return new self(
            $baseline,
            $manifestHash,
            $archiveHash,
            self::SOURCE_MANIFEST,
            count($listed),
            self::MANIFEST_NAME.' matched its trusted detached hash; '
                .count($listed).' entries verified with no missing, extra or duplicate paths',
            true,
        );
    }

    /**
     * @return array{0: array<string, true>, 1: list<string>}
     */
    private static function verifyManifestEntries(string $root, string $raw): array
    {
        $listed = [];
        $problems = [];
        $lines = preg_split('/\r\n|\r|\n/', $raw);

        if ($lines === false) {
            return [[], [self::MANIFEST_NAME.' could not be parsed']];
        }

        foreach ($lines as $number => $line) {
            if (trim($line) === '') {
                continue;
            }

            if (preg_match('/^([0-9a-f]{64})\s[\s*](.+)$/', $line, $m) !== 1) {
                $problems[] = 'line '.($number + 1).': unreadable manifest entry';

                continue;
            }

            [, $expected, $relative] = $m;
            $why = self::unsafePathReason($relative);

            if ($why !== null) {
                $problems[] = 'line '.($number + 1).': refused path ('.$why.'): '.$relative;

                continue;
            }

            if (isset($listed[$relative])) {
                $problems[] = $relative.': duplicate manifest entry';

                continue;
            }

            $listed[$relative] = true;
            $path = $root.'/'.$relative;

            if (! is_file($path) || is_link($path)) {
                $problems[] = $relative.': missing';

                continue;
            }

            /*
             * Belt and braces against a path that passed the textual checks but
             * still resolves outside the root, e.g. through a symlinked parent.
             */
            $real = realpath($path);

            if ($real === false || ! str_starts_with($real, $root.'/')) {
                $problems[] = $relative.': resolves outside the project root';

                continue;
            }

            if (! hash_equals($expected, (string) hash_file('sha256', $path))) {
                $problems[] = $relative.': checksum mismatch';
            }
        }

        return [$listed, $problems];
    }

    private static function isGitWorkingTree(string $root): bool
    {
        if (! is_dir($root.'/.git') && ! is_file($root.'/.git')) {
            return false;
        }

        return self::run('git -C '.escapeshellarg($root).' rev-parse --is-inside-work-tree')['code'] === 0;
    }

    private static function realRoot(string $root): string
    {
        $real = realpath($root);

        if ($real === false) {
            throw new RuntimeException('the project root '.$root.' does not exist.');
        }

        return rtrim($real, '/');
    }

    /**
     * @param  list<string>  $argv
     */
    private static function option(array $argv, string $name): ?string
    {
        $prefix = '--'.$name.'=';

        foreach ($argv as $argument) {
            if (str_starts_with($argument, $prefix)) {
                $value = trim(substr($argument, strlen($prefix)));

                return $value === '' ? null : $value;
            }
        }

        return null;
    }

    private static function environment(string $name): ?string
    {
        $value = getenv($name);

        return is_string($value) && trim($value) !== '' ? trim($value) : null;
    }

    private static function looksLikeCommit(string $candidate): bool
    {
        return preg_match('/^[0-9a-f]{40}$/', $candidate) === 1;
    }

    /**
     * @return array{code: int, output: string}
     */
    private static function run(string $command): array
    {
        $output = [];
        $code = 0;
        exec($command.' 2>&1', $output, $code);

        return ['code' => $code, 'output' => implode("\n", $output)];
    }
}
