<?php

declare(strict_types=1);

namespace App\Modules\Install\Services;

use RuntimeException;

/**
 * Generates and updates .env (spec 33.2).
 *
 * The hard rules, both from spec 33.2 / 33.3:
 *   - APP_KEY is generated ONLY for a new installation.
 *   - APP_KEY is NEVER overwritten during an upgrade.
 *
 * Violating the second silently destroys every encrypted phone number,
 * every encrypted MFA secret and every recovery code in the database, and the
 * damage is not visible until a user tries to log in.
 */
final class EnvWriter
{
    public function __construct(private readonly InstallState $state) {}

    /**
     * @param  array<string, string|int|bool|null>  $values
     */
    public function write(array $values): void
    {
        $path = base_path('.env');
        $isUpgrade = $this->state->mode() === 'upgrade';

        $existing = is_file($path) ? $this->parse((string) file_get_contents($path)) : [];

        foreach ((array) config('installer.upgrade.preserve', []) as $preservedKey) {
            $preservedKey = (string) $preservedKey;

            if ($isUpgrade && isset($existing[$preservedKey]) && $existing[$preservedKey] !== '') {
                // Explicitly drop any attempt to change it, even if a caller
                // passed one in.
                unset($values[$preservedKey]);
            }
        }

        if (! $isUpgrade && ! isset($values['APP_KEY']) && ($existing['APP_KEY'] ?? '') === '') {
            $values['APP_KEY'] = 'base64:'.base64_encode(random_bytes(32));
        }

        // PII and blind-index keys are independent of APP_KEY so PII can be
        // re-keyed without invalidating sessions and signed URLs.
        foreach (['MULKIHAWLER_PII_KEY', 'MULKIHAWLER_BLIND_INDEX_KEY'] as $key) {
            if (($existing[$key] ?? '') === '' && ! isset($values[$key])) {
                $values[$key] = base64_encode(random_bytes(32));
            }
        }

        $merged = array_merge($existing, array_map($this->stringify(...), $values));

        $this->atomicPut($path, $this->render($merged));

        $this->state->log('.env written', ['keys' => array_keys($values)]);
    }

    /** @return array<string, string> */
    public function parse(string $contents): array
    {
        $out = [];

        foreach (preg_split('/\R/', $contents) ?: [] as $line) {
            $line = trim($line);

            if ($line === '' || str_starts_with($line, '#') || ! str_contains($line, '=')) {
                continue;
            }

            [$key, $value] = explode('=', $line, 2);
            $key = trim($key);
            $value = trim($value);

            if (strlen($value) >= 2 && $value[0] === '"' && str_ends_with($value, '"')) {
                $value = substr($value, 1, -1);
            }

            $out[$key] = $value;
        }

        return $out;
    }

    /** @param array<string, string> $values */
    private function render(array $values): string
    {
        $lines = [
            '# Generated by the Mulkihawler installer on '.now()->toIso8601String(),
            '# Do not commit this file. See docs/ENVIRONMENT_REFERENCE.md.',
            '',
        ];

        foreach ($values as $key => $value) {
            $lines[] = $key.'='.$this->quote($value);
        }

        return implode("\n", $lines)."\n";
    }

    private function quote(string $value): string
    {
        return preg_match('/[\s#"\'$]/', $value) === 1
            ? '"'.str_replace('"', '\"', $value).'"'
            : $value;
    }

    private function stringify(string|int|bool|null $value): string
    {
        return match (true) {
            is_bool($value) => $value ? 'true' : 'false',
            $value === null => '',
            default => (string) $value,
        };
    }

    /**
     * Write to a temporary file and rename. A shared host can time out
     * mid-write; a half-written .env is unrecoverable without SSH, which is
     * exactly what the user does not have.
     */
    private function atomicPut(string $path, string $contents): void
    {
        $temp = $path.'.'.bin2hex(random_bytes(4)).'.tmp';

        if (file_put_contents($temp, $contents, LOCK_EX) === false) {
            throw new RuntimeException('Could not write the environment file. Check that the project root is writable.');
        }

        @chmod($temp, 0o640);

        if (! rename($temp, $path)) {
            @unlink($temp);

            throw new RuntimeException('Could not replace the environment file.');
        }
    }
}
