<?php

declare(strict_types=1);

/*
 * mbstring is a production requirement, and this script runs without it.
 *
 * A secret scan that fatals on a machine missing an optional extension is a
 * secret scan nobody runs — and this is the check most worth running on an
 * unfamiliar box.
 */
function safe_excerpt(string $value, int $length): string
{
    if (function_exists('mb_substr')) {
        return mb_substr($value, 0, $length);
    }

    // Back off until the cut is not mid-sequence, so the excerpt is short
    // rather than corrupt: these files are full of Sorani and Arabic text.
    $cut = substr($value, 0, $length);

    while ($cut !== '' && preg_match('//u', $cut) !== 1) {
        $cut = substr($cut, 0, -1);
    }

    return $cut;
}

/**
 * Committed-secret guard (spec 37.5: "No secrets in repository or client
 * bundles", 28.2 "All secrets in environment variables").
 *
 * Two classes of finding:
 *
 *   HARD FAIL — a credential-shaped literal in tracked source, or a file that
 *               should never be committed at all (.env, a key, a dump).
 *   WARN      — a suspicious pattern that is usually a false positive.
 *
 * A deliberately fake credential — a test fixture for the redactor, an example
 * in documentation — must carry an explicit marker on the same line or within
 * the three lines above it:
 *
 *     'openai key' => 'sk-not-a-real-key-0123456789', // SECRET-SCAN: fixture
 *
 * The marker is per-line rather than per-directory on purpose. Excluding the
 * whole tests/ tree would be easier and would also be the obvious place for a
 * real credential to hide.
 *
 * Runs with no dependencies so it works before `composer install`.
 *
 * Usage: php scripts/secret-scan.php [--warn-only]
 */
$root = dirname(__DIR__);
$warnOnly = in_array('--warn-only', $argv, true);

$skipDirs = ['vendor', 'node_modules', '.git', 'storage', 'public/build', 'bootstrap/cache', 'dist'];

/** Files that must never appear in the repository at all. */
$forbiddenFiles = [
    '.env',
    '.env.production',
    '.env.local',
    /*
     * Generated by the browser fixture seeder: a known test password and two
     * MFA seeds. It reached a delivered source archive once; this gate is what
     * makes that fail loudly rather than silently ship.
     */
    'tests/Browser/support/fixtures.json',
    'auth.json',
    'storage/installer/installed.lock',
];

/** @var array<string, array{pattern: string, label: string, hard: bool}> */
$rules = [
    'app_key' => [
        'pattern' => '/APP_KEY\s*=\s*["\']?base64:[A-Za-z0-9+\/=]{40,}/',
        'label' => 'Laravel APP_KEY literal',
        'hard' => true,
    ],
    'openai_key' => [
        'pattern' => '/\bsk-[A-Za-z0-9]{20,}/',
        'label' => 'OpenAI-style API key',
        'hard' => true,
    ],
    'google_key' => [
        'pattern' => '/\bAIza[0-9A-Za-z_\-]{33,}/',
        'label' => 'Google API key',
        'hard' => true,
    ],
    'telegram_token' => [
        'pattern' => '/\b\d{8,12}:[A-Za-z0-9_\-]{33,}\b/',
        'label' => 'Telegram bot token',
        'hard' => true,
    ],
    'aws_key' => [
        'pattern' => '/\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/',
        'label' => 'AWS access key id',
        'hard' => true,
    ],
    'private_key' => [
        'pattern' => '/-----BEGIN (?:RSA |EC |OPENSSH |PGP )?PRIVATE KEY-----/',
        'label' => 'private key block',
        'hard' => true,
    ],
    'db_url_creds' => [
        'pattern' => '/\b(?:mysql|postgres|postgresql|mongodb):\/\/[^:\s\'"]+:[^@\s\'"]{4,}@/',
        'label' => 'database URL with inline password',
        'hard' => true,
    ],
    'jwt' => [
        'pattern' => '/\beyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}/',
        'label' => 'JWT literal',
        'hard' => false,
    ],
    'hardcoded_password' => [
        // Assignment of a non-empty, non-placeholder password literal.
        'pattern' => '/(?:password|passwd|secret)\s*(?:=>|=|:)\s*[\'"](?!.*(?:example|changeme|placeholder|your[_\- ]|xxx|\.\.\.))[^\'"\s]{8,}[\'"]/i',
        'label' => 'hard-coded password literal',
        'hard' => false,
    ],
];

$scanExtensions = ['php', 'ts', 'js', 'vue', 'json', 'yml', 'yaml', 'neon', 'env', 'sh', 'md', 'blade.php'];

$acknowledgement = '/SECRET-SCAN:\s*fixture/i';

/*
 * A NARROW, SELF-LIMITING CLASSIFICATION FOR KEY NAMES.
 *
 * `private const PENDING_ADMIN_PASSWORD = 'install.pending_admin_password';`
 * is a session key, not a credential — but it matches the hard-coded password
 * rule, and a scanner that warns about something harmless every single run
 * trains people to ignore it, which is how the real finding gets missed.
 *
 * The exemption CANNOT be used to hide a secret. It requires BOTH an explicit
 * marker AND the literal itself to have the shape of a dotted identifier:
 * lowercase words joined by dots or underscores, nothing else. A real password
 * that satisfied that shape would be so weak it deserves to be flagged anyway.
 * A marker placed over an actual credential is refused and still reported.
 */
$keyNameAcknowledgement = '/SECRET-SCAN:\s*key-name/i';

/** Whether every quoted literal on the line is a dotted identifier. */
function is_key_name_literal(string $line): bool
{
    if (preg_match_all('/[\'"]([^\'"]+)[\'"]/', $line, $matches) !== 1) {
        return false;   // zero or several literals: too ambiguous to exempt
    }

    return preg_match('/^[a-z][a-z0-9_]*(?:[._][a-z0-9_]+)+$/', $matches[1][0]) === 1;
}

$hardFindings = [];
$warnFindings = [];
$acknowledged = 0;
$refusedAcknowledgements = [];

// --- forbidden files -----------------------------------------------------
foreach ($forbiddenFiles as $relative) {
    if (is_file($root.'/'.$relative)) {
        $hardFindings[] = [
            'file' => $relative,
            'line' => 0,
            'label' => 'file must never be committed',
            'excerpt' => '',
        ];
    }
}

// --- content scan --------------------------------------------------------
$iterator = new RecursiveIteratorIterator(
    new RecursiveCallbackFilterIterator(
        new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS),
        static function (SplFileInfo $file) use ($root, $skipDirs): bool {
            $relative = ltrim(str_replace($root, '', $file->getPathname()), '/');

            foreach ($skipDirs as $skip) {
                if ($relative === $skip || str_starts_with($relative, $skip.'/')) {
                    return false;
                }
            }

            return true;
        },
    ),
);

$scanned = 0;

/** @var SplFileInfo $file */
foreach ($iterator as $file) {
    if (! $file->isFile()) {
        continue;
    }

    $relative = ltrim(str_replace($root, '', $file->getPathname()), '/');
    $extension = strtolower($file->getExtension());

    if (! in_array($extension, $scanExtensions, true)) {
        continue;
    }

    // This script itself necessarily contains every pattern it looks for.
    if ($relative === 'scripts/secret-scan.php') {
        continue;
    }

    $scanned++;
    $lines = file($file->getPathname(), FILE_IGNORE_NEW_LINES) ?: [];

    foreach ($lines as $index => $line) {
        foreach ($rules as $ruleId => $rule) {
            if (preg_match($rule['pattern'], $line) !== 1) {
                continue;
            }

            // Explicit acknowledgement: same line, or up to three lines above.
            $context = implode("\n", array_slice($lines, max(0, $index - 3), 4));

            if (preg_match($acknowledgement, $context) === 1) {
                $acknowledged++;

                continue;
            }

            if ($ruleId === 'hardcoded_password' && preg_match($keyNameAcknowledgement, $context) === 1) {
                if (is_key_name_literal($line)) {
                    $acknowledged++;

                    continue;
                }

                // The marker is present but the literal is not a key name.
                // Report it anyway, and say the exemption was refused.
                $refusedAcknowledgements[] = $relative.':'.($index + 1);
            }

            $finding = [
                'file' => $relative,
                'line' => $index + 1,
                'label' => $rule['label'],
                'excerpt' => safe_excerpt(trim($line), 100),
            ];

            if ($rule['hard']) {
                $hardFindings[] = $finding;
            } else {
                $warnFindings[] = $finding;
            }
        }
    }
}

// --- report --------------------------------------------------------------
printf(
    "\nSecret scan — %d files inspected%s\n",
    $scanned,
    $acknowledged > 0 ? sprintf(', %d acknowledged fixture%s skipped', $acknowledged, $acknowledged === 1 ? '' : 's') : '',
);
echo str_repeat('─', 68), "\n";

foreach ($refusedAcknowledgements as $refused) {
    printf("  \033[31mNOTE\033[0m  %s  a key-name exemption was REFUSED: the literal is not an identifier\n", $refused);
}

foreach ($warnFindings as $f) {
    printf("  \033[33mWARN\033[0m  %s:%d  %s\n", $f['file'], $f['line'], $f['label']);
}

foreach ($hardFindings as $f) {
    printf("  \033[31mFAIL\033[0m  %s:%d  %s\n", $f['file'], $f['line'] ?: '-', $f['label']);

    if ($f['excerpt'] !== '') {
        echo '          '.$f['excerpt']."\n";
    }
}

echo str_repeat('─', 68), "\n";

if ($hardFindings === []) {
    printf(
        "  \033[42;30m PASS \033[0m  no committed secrets%s\n\n",
        $warnFindings === [] ? '' : sprintf(' (%d warning%s)', count($warnFindings), count($warnFindings) === 1 ? '' : 's'),
    );
    exit(0);
}

printf("  \033[41;37m FAIL \033[0m  %d secret(s) found in tracked files\n\n", count($hardFindings));
exit($warnOnly ? 0 : 1);
